In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('data4.csv', skiprows=[0], encoding = 'ISO-8859-1')
cols = ['Natural', 'XS', 'S', 'M', 'L', 'Toe', 'Heel', 'Ascending', 'Descending']

In [3]:
data.head()

,Power [W / kg],% Gait Cycle,Natural,Unnamed: 3,Unnamed: 4,XS,Unnamed: 6,Unnamed: 7,S,Unnamed: 9,...,Unnamed: 46,Heel.1,Unnamed: 48,Unnamed: 49,Ascending.1,Unnamed: 51,Unnamed: 52,Descending.1,Unnamed: 54,Unnamed: 55
0,Hip,0%,-0.12,0.05,0.21,-0.03,0.02,0.06,-0.05,0.06,...,0.33,-0.07,0.24,0.55,-0.13,-0.07,-0.01,-0.07,-0.03,0.01
1,Hip,1%,-0.13,0.05,0.23,-0.02,0.03,0.08,-0.03,0.07,...,0.44,-0.05,0.22,0.49,-0.10,-0.05,0.01,-0.06,-0.01,0.03
2,Hip,2%,-0.15,0.05,0.25,-0.02,0.04,0.10,-0.02,0.09,...,0.55,-0.12,0.12,0.36,-0.08,-0.02,0.04,-0.04,0.00,0.04
3,Hip,3%,-0.15,0.06,0.28,-0.01,0.06,0.13,0.00,0.10,...,0.65,-0.35,-0.01,0.33,-0.05,0.00,0.05,-0.04,0.00,0.05
4,Hip,4%,-0.14,0.08,0.30,0.00,0.08,0.16,0.01,0.12,...,0.73,-0.49,-0.08,0.32,-0.03,0.01,0.06,-0.06,0.00,0.06

In [4]:
def modifyCsv(data):
    t1 = 3
    t2 = 4
    #for young
    for i in cols:
        data[i] = (data[i] + data['Unnamed: ' + str(t1)] + data['Unnamed: ' + str(t2)])/3
        data.drop(['Unnamed: ' + str(t1), 'Unnamed: ' + str(t2)], inplace = True, axis = 1)
        t1 += 3
        t2 += 3
        
    #for adult
    for i in cols:
        data[i + '.1'] = (data[i + '.1'] + data['Unnamed: ' + str(t1)] + data['Unnamed: ' + str(t2)])/3
        data.drop(['Unnamed: ' + str(t1), 'Unnamed: ' + str(t2)], inplace = True, axis = 1)
        t1 += 3
        t2 += 3
        
    
    return data

In [5]:
copy_data = data.copy()
copy_data = modifyCsv(copy_data)
copy_data.head()

,Power [W / kg],% Gait Cycle,Natural,XS,S,M,L,Toe,Heel,Ascending,Descending,Natural.1,XS.1,S.1,M.1,L.1,Toe.1,Heel.1,Ascending.1,Descending.1
0,Hip,0%,0.046667,0.016667,0.063333,0.10,0.116667,0.090000,0.223333,0.010000,0.036667,-0.02,0.020000,0.02,-0.073333,0.170000,0.126667,0.240000,-0.070000,-0.030000
1,Hip,1%,0.050000,0.030000,0.073333,0.11,0.143333,0.140000,0.216667,0.050000,0.046667,0.03,0.050000,0.07,-0.010000,0.226667,0.196667,0.220000,-0.046667,-0.013333
2,Hip,2%,0.050000,0.040000,0.086667,0.12,0.156667,0.200000,0.200000,0.090000,0.043333,0.08,0.093333,0.12,0.050000,0.150000,0.263333,0.120000,-0.020000,0.000000
3,Hip,3%,0.063333,0.060000,0.100000,0.13,0.176667,0.276667,0.170000,0.116667,0.026667,0.12,0.123333,0.15,0.090000,0.000000,0.333333,-0.010000,0.000000,0.003333
4,Hip,4%,0.080000,0.080000,0.116667,0.15,0.200000,0.353333,0.136667,0.143333,-0.003333,0.14,0.130000,0.16,0.100000,-0.110000,0.406667,-0.083333,0.013333,0.000000

In [6]:
adult = copy_data.copy()
young = copy_data.copy()

In [7]:
young.drop([i + '.1' for i in cols], axis=1, inplace=True)
young['Target'] = 'Young'
young.head()

,Power [W / kg],% Gait Cycle,Natural,XS,S,M,L,Toe,Heel,Ascending,Descending,Target
0,Hip,0%,0.046667,0.016667,0.063333,0.10,0.116667,0.090000,0.223333,0.010000,0.036667,Young
1,Hip,1%,0.050000,0.030000,0.073333,0.11,0.143333,0.140000,0.216667,0.050000,0.046667,Young
2,Hip,2%,0.050000,0.040000,0.086667,0.12,0.156667,0.200000,0.200000,0.090000,0.043333,Young
3,Hip,3%,0.063333,0.060000,0.100000,0.13,0.176667,0.276667,0.170000,0.116667,0.026667,Young
4,Hip,4%,0.080000,0.080000,0.116667,0.15,0.200000,0.353333,0.136667,0.143333,-0.003333,Young

In [8]:
for i in cols:
    adult[i] = adult[i + '.1']
    adult.drop([i + '.1'], inplace=True, axis=1)
adult['Target'] = 'Adult'

In [9]:
desired_data = pd.concat([young, adult], ignore_index=True)
desired_data.head()

,Power [W / kg],% Gait Cycle,Natural,XS,S,M,L,Toe,Heel,Ascending,Descending,Target
0,Hip,0%,0.046667,0.016667,0.063333,0.10,0.116667,0.090000,0.223333,0.010000,0.036667,Young
1,Hip,1%,0.050000,0.030000,0.073333,0.11,0.143333,0.140000,0.216667,0.050000,0.046667,Young
2,Hip,2%,0.050000,0.040000,0.086667,0.12,0.156667,0.200000,0.200000,0.090000,0.043333,Young
3,Hip,3%,0.063333,0.060000,0.100000,0.13,0.176667,0.276667,0.170000,0.116667,0.026667,Young
4,Hip,4%,0.080000,0.080000,0.116667,0.15,0.200000,0.353333,0.136667,0.143333,-0.003333,Young

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

In [11]:
X = desired_data[cols]
Y = desired_data['Target']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, random_state = 0)

In [15]:
mod = DecisionTreeClassifier().fit(X_train, Y_train)

In [16]:
predict = mod.predict(X_test)

In [17]:
mod.score(X_test, Y_test)

0.7105263157894737